name: BoatMapAnimator
main: boatmapanimator.BoatMapAnimatorPlugin
version: 1.0
api-version: 1.20
commands:
  boatmap:
    usage: /boatmap generate <framesDir> [x y z] [repeat]
    description: Generate animated map art track
